<a href="https://colab.research.google.com/github/joanby/python-ml-course/blob/master/notebooks/T4%20-%204%20-%20Linear%20Regression%20-%20SciKit-Learn-Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clonamos el repositorio para obtener los dataSet

In [1]:
!git clone https://github.com/joanby/python-ml-course.git

Cloning into 'python-ml-course'...
remote: Enumerating objects: 17706, done.
remote: Total 17706 (delta 0), reused 0 (delta 0), pack-reused 17706
Receiving objects: 100% (17706/17706), 523.15 MiB | 16.98 MiB/s, done.
Resolving deltas: 100% (333/333), done.
Checking out files: 100% (16940/16940), done.


# Damos acceso a nuestro Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
# Test it
!ls '/content/drive/My Drive' 

In [ ]:
from google.colab import files # Para manejar los archivos y, por ejemplo, exportar a su navegador
import glob # Para manejar los archivos y, por ejemplo, exportar a su navegador
from google.colab import drive # Montar tu Google drive

# Regresión lineal en Python
## El paquete scikit-learn para regresión lineal y la selección de rasgos

In [4]:
from sklearn.feature_selection import RFE #Recursive Feature Elimination
from sklearn.svm import SVR #Super Vector Machine -- Super Vector Classification
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("/content/python-ml-course/datasets/ads/Advertising.csv")

In [6]:
#Las cloumnas de predicción
feature_cols = ["TV", "Radio", "Newspaper"]

In [7]:
X = data[feature_cols]
Y = data["Sales"]

In [8]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, n_features_to_select=2, step=1)
selector = selector.fit(X,Y)

In [9]:
selector.support_

array([ True,  True, False])

In [10]:
selector.ranking_

array([1, 1, 2])

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
X_pred = X[["TV", "Radio"]]

In [13]:
lm = LinearRegression()
lm.fit(X_pred, Y)

LinearRegression()

In [14]:
lm.intercept_

2.9210999124051362

In [15]:
lm.coef_

array([0.04575482, 0.18799423])

In [16]:
lm.score(X_pred, Y)

0.8971942610828957